package bot;

import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.imageio.ImageIO;

import org.apache.commons.io.FilenameUtils;
import org.apache.commons.io.IOUtils;

public class URLImageUtils {

	private static Map<String, String> mimeMap = new HashMap<String, String>();
	static {
		// Build mime map
		mimeMap.put("123", "application/vnd.lotus-1-2-3");
		mimeMap.put("3dml", "text/vnd.in3d.3dml");
		mimeMap.put("3ds", "image/x-3ds");
		mimeMap.put("3g2", "video/3gpp2");
		mimeMap.put("3gp", "video/3gpp");
		mimeMap.put("7z", "application/x-7z-compressed");
		mimeMap.put("aab", "application/x-authorware-bin");
		mimeMap.put("aac", "audio/x-aac");
		mimeMap.put("aam", "application/x-authorware-map");
		mimeMap.put("aas", "application/x-authorware-seg");
		mimeMap.put("abw", "application/x-abiword");
		mimeMap.put("ac", "application/pkix-attr-cert");
		mimeMap.put("acc", "application/vnd.americandynamics.acc");
		mimeMap.put("ace", "application/x-ace-compressed");
		mimeMap.put("acu", "application/vnd.acucobol");
		mimeMap.put("acutc", "application/vnd.acucorp");
		mimeMap.put("adp", "audio/adpcm");
		mimeMap.put("aep", "application/vnd.audiograph");
		mimeMap.put("afm", "application/x-font-type1");
		mimeMap.put("afp", "application/vnd.ibm.modcap");
		mimeMap.put("ahead", "application/vnd.ahead.space");
		mimeMap.put("ai", "application/postscript");
		mimeMap.put("aif", "audio/x-aiff");
		mimeMap.put("aifc", "audio/x-aiff");
		mimeMap.put("aiff", "audio/x-aiff");
		mimeMap.put("air", "application/vnd.adobe.air-application-installer-package+zip");
		mimeMap.put("ait", "application/vnd.dvb.ait");
		mimeMap.put("ami", "application/vnd.amiga.ami");
		mimeMap.put("apk", "application/vnd.android.package-archive");
		mimeMap.put("appcache", "text/cache-manifest");
		mimeMap.put("application", "application/x-ms-application");
		mimeMap.put("apr", "application/vnd.lotus-approach");
		mimeMap.put("arc", "application/x-freearc");
		mimeMap.put("asc", "application/pgp-signature");
		mimeMap.put("asf", "video/x-ms-asf");
		mimeMap.put("asm", "text/x-asm");
		mimeMap.put("aso", "application/vnd.accpac.simply.aso");
		mimeMap.put("asx", "video/x-ms-asf");
		mimeMap.put("atc", "application/vnd.acucorp");
		mimeMap.put("atom", "application/atom+xml");
		mimeMap.put("atomcat", "application/atomcat+xml");
		mimeMap.put("atomsvc", "application/atomsvc+xml");
		mimeMap.put("atx", "application/vnd.antix.game-component");
		mimeMap.put("au", "audio/basic");
		mimeMap.put("avi", "video/x-msvideo");
		mimeMap.put("aw", "application/applixware");
		mimeMap.put("azf", "application/vnd.airzip.filesecure.azf");
		mimeMap.put("azs", "application/vnd.airzip.filesecure.azs");
		mimeMap.put("azw", "application/vnd.amazon.ebook");
		mimeMap.put("bat", "application/x-msdownload");
		mimeMap.put("bcpio", "application/x-bcpio");
		mimeMap.put("bdf", "application/x-font-bdf");
		mimeMap.put("bdm", "application/vnd.syncml.dm+wbxml");
		mimeMap.put("bed", "application/vnd.realvnc.bed");
		mimeMap.put("bh2", "application/vnd.fujitsu.oasysprs");
		mimeMap.put("bin", "application/octet-stream");
		mimeMap.put("blb", "application/x-blorb");
		mimeMap.put("blorb", "application/x-blorb");
		mimeMap.put("bmi", "application/vnd.bmi");
		mimeMap.put("bmp", "image/bmp");
		mimeMap.put("book", "application/vnd.framemaker");
		mimeMap.put("box", "application/vnd.previewsystems.box");
		mimeMap.put("boz", "application/x-bzip2");
		mimeMap.put("bpk", "application/octet-stream");
		mimeMap.put("btif", "image/prs.btif");
		mimeMap.put("bz2", "application/x-bzip2");
		mimeMap.put("bz", "application/x-bzip");
		mimeMap.put("c11amc", "application/vnd.cluetrust.cartomobile-config");
		mimeMap.put("c11amz", "application/vnd.cluetrust.cartomobile-config-pkg");
		mimeMap.put("c4d", "application/vnd.clonk.c4group");
		mimeMap.put("c4f", "application/vnd.clonk.c4group");
		mimeMap.put("c4g", "application/vnd.clonk.c4group");
		mimeMap.put("c4p", "application/vnd.clonk.c4group");
		mimeMap.put("c4u", "application/vnd.clonk.c4group");
		mimeMap.put("cab", "application/vnd.ms-cab-compressed");
		mimeMap.put("caf", "audio/x-caf");
		mimeMap.put("cap", "application/vnd.tcpdump.pcap");
		mimeMap.put("car", "application/vnd.curl.car");
		mimeMap.put("cat", "application/vnd.ms-pki.seccat");
		mimeMap.put("cb7", "application/x-cbr");
		mimeMap.put("cba", "application/x-cbr");
		mimeMap.put("cbr", "application/x-cbr");
		mimeMap.put("cbt", "application/x-cbr");
		mimeMap.put("cbz", "application/x-cbr");
		mimeMap.put("cct", "application/x-director");
		mimeMap.put("cc", "text/x-c");
		mimeMap.put("ccxml", "application/ccxml+xml");
		mimeMap.put("cdbcmsg", "application/vnd.contact.cmsg");
		mimeMap.put("cdf", "application/x-netcdf");
		mimeMap.put("cdkey", "application/vnd.mediastation.cdkey");
		mimeMap.put("cdmia", "application/cdmi-capability");
		mimeMap.put("cdmic", "application/cdmi-container");
		mimeMap.put("cdmid", "application/cdmi-domain");
		mimeMap.put("cdmio", "application/cdmi-object");
		mimeMap.put("cdmiq", "application/cdmi-queue");
		mimeMap.put("cdx", "chemical/x-cdx");
		mimeMap.put("cdxml", "application/vnd.chemdraw+xml");
		mimeMap.put("cdy", "application/vnd.cinderella");
		mimeMap.put("cer", "application/pkix-cert");
		mimeMap.put("cfs", "application/x-cfs-compressed");
		mimeMap.put("cgm", "image/cgm");
		mimeMap.put("chat", "application/x-chat");
		mimeMap.put("chm", "application/vnd.ms-htmlhelp");
		mimeMap.put("chrt", "application/vnd.kde.kchart");
		mimeMap.put("cif", "chemical/x-cif");
		mimeMap.put("cii", "application/vnd.anser-web-certificate-issue-initiation");
		mimeMap.put("cil", "application/vnd.ms-artgalry");
		mimeMap.put("cla", "application/vnd.claymore");
		mimeMap.put("class", "application/java-vm");
		mimeMap.put("clkk", "application/vnd.crick.clicker.keyboard");
		mimeMap.put("clkp", "application/vnd.crick.clicker.palette");
		mimeMap.put("clkt", "application/vnd.crick.clicker.template");
		mimeMap.put("clkw", "application/vnd.crick.clicker.wordbank");
		mimeMap.put("clkx", "application/vnd.crick.clicker");
		mimeMap.put("clp", "application/x-msclip");
		mimeMap.put("cmc", "application/vnd.cosmocaller");
		mimeMap.put("cmdf", "chemical/x-cmdf");
		mimeMap.put("cml", "chemical/x-cml");
		mimeMap.put("cmp", "application/vnd.yellowriver-custom-menu");
		mimeMap.put("cmx", "image/x-cmx");
		mimeMap.put("cod", "application/vnd.rim.cod");
		mimeMap.put("com", "application/x-msdownload");
		mimeMap.put("conf", "text/plain");
		mimeMap.put("cpio", "application/x-cpio");
		mimeMap.put("cpp", "text/x-c");
		mimeMap.put("cpt", "application/mac-compactpro");
		mimeMap.put("crd", "application/x-mscardfile");
		mimeMap.put("crl", "application/pkix-crl");
		mimeMap.put("crt", "application/x-x509-ca-cert");
		mimeMap.put("cryptonote", "application/vnd.rig.cryptonote");
		mimeMap.put("csh", "application/x-csh");
		mimeMap.put("csml", "chemical/x-csml");
		mimeMap.put("csp", "application/vnd.commonspace");
		mimeMap.put("css", "text/css");
		mimeMap.put("cst", "application/x-director");
		mimeMap.put("csv", "text/csv");
		mimeMap.put("c", "text/x-c");
		mimeMap.put("cu", "application/cu-seeme");
		mimeMap.put("curl", "text/vnd.curl");
		mimeMap.put("cww", "application/prs.cww");
		mimeMap.put("cxt", "application/x-director");
		mimeMap.put("cxx", "text/x-c");
		mimeMap.put("dae", "model/vnd.collada+xml");
		mimeMap.put("daf", "application/vnd.mobius.daf");
		mimeMap.put("dart", "application/vnd.dart");
		mimeMap.put("dataless", "application/vnd.fdsn.seed");
		mimeMap.put("davmount", "application/davmount+xml");
		mimeMap.put("dbk", "application/docbook+xml");
		mimeMap.put("dcr", "application/x-director");
		mimeMap.put("dcurl", "text/vnd.curl.dcurl");
		mimeMap.put("dd2", "application/vnd.oma.dd2+xml");
		mimeMap.put("ddd", "application/vnd.fujixerox.ddd");
		mimeMap.put("deb", "application/x-debian-package");
		mimeMap.put("def", "text/plain");
		mimeMap.put("deploy", "application/octet-stream");
		mimeMap.put("der", "application/x-x509-ca-cert");
		mimeMap.put("dfac", "application/vnd.dreamfactory");
		mimeMap.put("dgc", "application/x-dgc-compressed");
		mimeMap.put("dic", "text/x-c");
		mimeMap.put("dir", "application/x-director");
		mimeMap.put("dis", "application/vnd.mobius.dis");
		mimeMap.put("dist", "application/octet-stream");
		mimeMap.put("distz", "application/octet-stream");
		mimeMap.put("djv", "image/vnd.djvu");
		mimeMap.put("djvu", "image/vnd.djvu");
		mimeMap.put("dll", "application/x-msdownload");
		mimeMap.put("dmg", "application/x-apple-diskimage");
		mimeMap.put("dmp", "application/vnd.tcpdump.pcap");
		mimeMap.put("dms", "application/octet-stream");
		mimeMap.put("dna", "application/vnd.dna");
		mimeMap.put("doc", "application/msword");
		mimeMap.put("docm", "application/vnd.ms-word.document.macroenabled.12");
		mimeMap.put("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
		mimeMap.put("dot", "application/msword");
		mimeMap.put("dotm", "application/vnd.ms-word.template.macroenabled.12");
		mimeMap.put("dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template");
		mimeMap.put("dp", "application/vnd.osgi.dp");
		mimeMap.put("dpg", "application/vnd.dpgraph");
		mimeMap.put("dra", "audio/vnd.dra");
		mimeMap.put("dsc", "text/prs.lines.tag");
		mimeMap.put("dssc", "application/dssc+der");
		mimeMap.put("dtb", "application/x-dtbook+xml");
		mimeMap.put("dtd", "application/xml-dtd");
		mimeMap.put("dts", "audio/vnd.dts");
		mimeMap.put("dtshd", "audio/vnd.dts.hd");
		mimeMap.put("dump", "application/octet-stream");
		mimeMap.put("dvb", "video/vnd.dvb.file");
		mimeMap.put("dvi", "application/x-dvi");
		mimeMap.put("dwf", "model/vnd.dwf");
		mimeMap.put("dwg", "image/vnd.dwg");
		mimeMap.put("dxf", "image/vnd.dxf");
		mimeMap.put("dxp", "application/vnd.spotfire.dxp");
		mimeMap.put("dxr", "application/x-director");
		mimeMap.put("ecelp4800", "audio/vnd.nuera.ecelp4800");
		mimeMap.put("ecelp7470", "audio/vnd.nuera.ecelp7470");
		mimeMap.put("ecelp9600", "audio/vnd.nuera.ecelp9600");
		mimeMap.put("ecma", "application/ecmascript");
		mimeMap.put("edm", "application/vnd.novadigm.edm");
		mimeMap.put("edx", "application/vnd.novadigm.edx");
		mimeMap.put("efif", "application/vnd.picsel");
		mimeMap.put("ei6", "application/vnd.pg.osasli");
		mimeMap.put("elc", "application/octet-stream");
		mimeMap.put("emf", "application/x-msmetafile");
		mimeMap.put("eml", "message/rfc822");
		mimeMap.put("emma", "application/emma+xml");
		mimeMap.put("emz", "application/x-msmetafile");
		mimeMap.put("eol", "audio/vnd.digital-winds");
		mimeMap.put("eot", "application/vnd.ms-fontobject");
		mimeMap.put("eps", "application/postscript");
		mimeMap.put("epub", "application/epub+zip");
		mimeMap.put("es3", "application/vnd.eszigno3+xml");
		mimeMap.put("esa", "application/vnd.osgi.subsystem");
		mimeMap.put("esf", "application/vnd.epson.esf");
		mimeMap.put("et3", "application/vnd.eszigno3+xml");
		mimeMap.put("etx", "text/x-setext");
		mimeMap.put("eva", "application/x-eva");
		mimeMap.put("evy", "application/x-envoy");
		mimeMap.put("exe", "application/x-msdownload");
		mimeMap.put("exi", "application/exi");
		mimeMap.put("ext", "application/vnd.novadigm.ext");
		mimeMap.put("ez2", "application/vnd.ezpix-album");
		mimeMap.put("ez3", "application/vnd.ezpix-package");
		mimeMap.put("ez", "application/andrew-inset");
		mimeMap.put("f4v", "video/x-f4v");
		mimeMap.put("f77", "text/x-fortran");
		mimeMap.put("f90", "text/x-fortran");
		mimeMap.put("fbs", "image/vnd.fastbidsheet");
		mimeMap.put("fcdt", "application/vnd.adobe.formscentral.fcdt");
		mimeMap.put("fcs", "application/vnd.isac.fcs");
		mimeMap.put("fdf", "application/vnd.fdf");
		mimeMap.put("fe_launch", "application/vnd.denovo.fcselayout-link");
		mimeMap.put("fg5", "application/vnd.fujitsu.oasysgp");
		mimeMap.put("fgd", "application/x-director");
		mimeMap.put("fh4", "image/x-freehand");
		mimeMap.put("fh5", "image/x-freehand");
		mimeMap.put("fh7", "image/x-freehand");
		mimeMap.put("fhc", "image/x-freehand");
		mimeMap.put("fh", "image/x-freehand");
		mimeMap.put("fig", "application/x-xfig");
		mimeMap.put("flac", "audio/x-flac");
		mimeMap.put("fli", "video/x-fli");
		mimeMap.put("flo", "application/vnd.micrografx.flo");
		mimeMap.put("flv", "video/x-flv");
		mimeMap.put("flw", "application/vnd.kde.kivio");
		mimeMap.put("flx", "text/vnd.fmi.flexstor");
		mimeMap.put("fly", "text/vnd.fly");
		mimeMap.put("fm", "application/vnd.framemaker");
		mimeMap.put("fnc", "application/vnd.frogans.fnc");
		mimeMap.put("for", "text/x-fortran");
		mimeMap.put("fpx", "image/vnd.fpx");
		mimeMap.put("frame", "application/vnd.framemaker");
		mimeMap.put("fsc", "application/vnd.fsc.weblaunch");
		mimeMap.put("fst", "image/vnd.fst");
		mimeMap.put("ftc", "application/vnd.fluxtime.clip");
		mimeMap.put("f", "text/x-fortran");
		mimeMap.put("fti", "application/vnd.anser-web-funds-transfer-initiation");
		mimeMap.put("fvt", "video/vnd.fvt");
		mimeMap.put("fxp", "application/vnd.adobe.fxp");
		mimeMap.put("fxpl", "application/vnd.adobe.fxp");
		mimeMap.put("fzs", "application/vnd.fuzzysheet");
		mimeMap.put("g2w", "application/vnd.geoplan");
		mimeMap.put("g3", "image/g3fax");
		mimeMap.put("g3w", "application/vnd.geospace");
		mimeMap.put("gac", "application/vnd.groove-account");
		mimeMap.put("gam", "application/x-tads");
		mimeMap.put("gbr", "application/rpki-ghostbusters");
		mimeMap.put("gca", "application/x-gca-compressed");
		mimeMap.put("gdl", "model/vnd.gdl");
		mimeMap.put("geo", "application/vnd.dynageo");
		mimeMap.put("gex", "application/vnd.geometry-explorer");
		mimeMap.put("ggb", "application/vnd.geogebra.file");
		mimeMap.put("ggt", "application/vnd.geogebra.tool");
		mimeMap.put("ghf", "application/vnd.groove-help");
		mimeMap.put("gif", "image/gif");
		mimeMap.put("gim", "application/vnd.groove-identity-message");
		mimeMap.put("gml", "application/gml+xml");
		mimeMap.put("gmx", "application/vnd.gmx");
		mimeMap.put("gnumeric", "application/x-gnumeric");
		mimeMap.put("gph", "application/vnd.flographit");
		mimeMap.put("gpx", "application/gpx+xml");
		mimeMap.put("gqf", "application/vnd.grafeq");
		mimeMap.put("gqs", "application/vnd.grafeq");
		mimeMap.put("gram", "application/srgs");
		mimeMap.put("gramps", "application/x-gramps-xml");
		mimeMap.put("gre", "application/vnd.geometry-explorer");
		mimeMap.put("grv", "application/vnd.groove-injector");
		mimeMap.put("grxml", "application/srgs+xml");
		mimeMap.put("gsf", "application/x-font-ghostscript");
		mimeMap.put("gtar", "application/x-gtar");
		mimeMap.put("gtm", "application/vnd.groove-tool-message");
		mimeMap.put("gtw", "model/vnd.gtw");
		mimeMap.put("gv", "text/vnd.graphviz");
		mimeMap.put("gxf", "application/gxf");
		mimeMap.put("gxt", "application/vnd.geonext");
		mimeMap.put("h261", "video/h261");
		mimeMap.put("h263", "video/h263");
		mimeMap.put("h264", "video/h264");
		mimeMap.put("hal", "application/vnd.hal+xml");
		mimeMap.put("hbci", "application/vnd.hbci");
		mimeMap.put("hdf", "application/x-hdf");
		mimeMap.put("hh", "text/x-c");
		mimeMap.put("hlp", "application/winhlp");
		mimeMap.put("hpgl", "application/vnd.hp-hpgl");
		mimeMap.put("hpid", "application/vnd.hp-hpid");
		mimeMap.put("hps", "application/vnd.hp-hps");
		mimeMap.put("hqx", "application/mac-binhex40");
		mimeMap.put("h", "text/x-c");
		mimeMap.put("htke", "application/vnd.kenameaapp");
		mimeMap.put("html", "text/html");
		mimeMap.put("htm", "text/html");
		mimeMap.put("hvd", "application/vnd.yamaha.hv-dic");
		mimeMap.put("hvp", "application/vnd.yamaha.hv-voice");
		mimeMap.put("hvs", "application/vnd.yamaha.hv-script");
		mimeMap.put("i2g", "application/vnd.intergeo");
		mimeMap.put("icc", "application/vnd.iccprofile");
		mimeMap.put("ice", "x-conference/x-cooltalk");
		mimeMap.put("icm", "application/vnd.iccprofile");
		mimeMap.put("ico", "image/x-icon");
		mimeMap.put("ics", "text/calendar");
		mimeMap.put("ief", "image/ief");
		mimeMap.put("ifb", "text/calendar");
		mimeMap.put("ifm", "application/vnd.shana.informed.formdata");
		mimeMap.put("iges", "model/iges");
		mimeMap.put("igl", "application/vnd.igloader");
		mimeMap.put("igm", "application/vnd.insors.igm");
		mimeMap.put("igs", "model/iges");
		mimeMap.put("igx", "application/vnd.micrografx.igx");
		mimeMap.put("iif", "application/vnd.shana.informed.interchange");
		mimeMap.put("imp", "application/vnd.accpac.simply.imp");
		mimeMap.put("ims", "application/vnd.ms-ims");
		mimeMap.put("ink", "application/inkml+xml");
		mimeMap.put("inkml", "application/inkml+xml");
		mimeMap.put("install", "application/x-install-instructions");
		mimeMap.put("in", "text/plain");
		mimeMap.put("iota", "application/vnd.astraea-software.iota");
		mimeMap.put("ipfix", "application/ipfix");
		mimeMap.put("ipk", "application/vnd.shana.informed.package");
		mimeMap.put("irm", "application/vnd.ibm.rights-management");
		mimeMap.put("irp", "application/vnd.irepository.package+xml");
		mimeMap.put("iso", "application/x-iso9660-image");
		mimeMap.put("itp", "application/vnd.shana.informed.formtemplate");
		mimeMap.put("ivp", "application/vnd.immervision-ivp");
		mimeMap.put("ivu", "application/vnd.immervision-ivu");
		mimeMap.put("jad", "text/vnd.sun.j2me.app-descriptor");
		mimeMap.put("jam", "application/vnd.jam");
		mimeMap.put("jar", "application/java-archive");
		mimeMap.put("java", "text/x-java-source");
		mimeMap.put("jisp", "application/vnd.jisp");
		mimeMap.put("jlt", "application/vnd.hp-jlyt");
		mimeMap.put("jnlp", "application/x-java-jnlp-file");
		mimeMap.put("joda", "application/vnd.joost.joda-archive");
		mimeMap.put("jpeg", "image/jpeg");
		mimeMap.put("jpe", "image/jpeg");
		mimeMap.put("jpg", "image/jpeg");
		mimeMap.put("jpgm", "video/jpm");
		mimeMap.put("jpgv", "video/jpeg");
		mimeMap.put("jpm", "video/jpm");
		mimeMap.put("js", "application/javascript");
		mimeMap.put("json", "application/json");
		mimeMap.put("jsonml", "application/jsonml+json");
		mimeMap.put("kar", "audio/midi");
		mimeMap.put("karbon", "application/vnd.kde.karbon");
		mimeMap.put("kfo", "application/vnd.kde.kformula");
		mimeMap.put("kia", "application/vnd.kidspiration");
		mimeMap.put("kml", "application/vnd.google-earth.kml+xml");
		mimeMap.put("kmz", "application/vnd.google-earth.kmz");
		mimeMap.put("kne", "application/vnd.kinar");
		mimeMap.put("knp", "application/vnd.kinar");
		mimeMap.put("kon", "application/vnd.kde.kontour");
		mimeMap.put("kpr", "application/vnd.kde.kpresenter");
		mimeMap.put("kpt", "application/vnd.kde.kpresenter");
		mimeMap.put("kpxx", "application/vnd.ds-keypoint");
		mimeMap.put("ksp", "application/vnd.kde.kspread");
		mimeMap.put("ktr", "application/vnd.kahootz");
		mimeMap.put("ktx", "image/ktx");
		mimeMap.put("ktz", "application/vnd.kahootz");
		mimeMap.put("kwd", "application/vnd.kde.kword");
		mimeMap.put("kwt", "application/vnd.kde.kword");
		mimeMap.put("lasxml", "application/vnd.las.las+xml");
		mimeMap.put("latex", "application/x-latex");
		mimeMap.put("lbd", "application/vnd.llamagraphics.life-balance.desktop");
		mimeMap.put("lbe", "application/vnd.llamagraphics.life-balance.exchange+xml");
		mimeMap.put("les", "application/vnd.hhe.lesson-player");
		mimeMap.put("lha", "application/x-lzh-compressed");
		mimeMap.put("link66", "application/vnd.route66.link66+xml");
		mimeMap.put("list3820", "application/vnd.ibm.modcap");
		mimeMap.put("listafp", "application/vnd.ibm.modcap");
		mimeMap.put("list", "text/plain");
		mimeMap.put("lnk", "application/x-ms-shortcut");
		mimeMap.put("log", "text/plain");
		mimeMap.put("lostxml", "application/lost+xml");
		mimeMap.put("lrf", "application/octet-stream");
		mimeMap.put("lrm", "application/vnd.ms-lrm");
		mimeMap.put("ltf", "application/vnd.frogans.ltf");
		mimeMap.put("lvp", "audio/vnd.lucent.voice");
		mimeMap.put("lwp", "application/vnd.lotus-wordpro");
		mimeMap.put("lzh", "application/x-lzh-compressed");
		mimeMap.put("m13", "application/x-msmediaview");
		mimeMap.put("m14", "application/x-msmediaview");
		mimeMap.put("m1v", "video/mpeg");
		mimeMap.put("m21", "application/mp21");
		mimeMap.put("m2a", "audio/mpeg");
		mimeMap.put("m2v", "video/mpeg");
		mimeMap.put("m3a", "audio/mpeg");
		mimeMap.put("m3u8", "application/vnd.apple.mpegurl");
		mimeMap.put("m3u", "audio/x-mpegurl");
		mimeMap.put("m4a", "audio/mp4");
		mimeMap.put("m4u", "video/vnd.mpegurl");
		mimeMap.put("m4v", "video/x-m4v");
		mimeMap.put("ma", "application/mathematica");
		mimeMap.put("mads", "application/mads+xml");
		mimeMap.put("mag", "application/vnd.ecowin.chart");
		mimeMap.put("maker", "application/vnd.framemaker");
		mimeMap.put("man", "text/troff");
		mimeMap.put("mar", "application/octet-stream");
		mimeMap.put("mathml", "application/mathml+xml");
		mimeMap.put("mb", "application/mathematica");
		mimeMap.put("mbk", "application/vnd.mobius.mbk");
		mimeMap.put("mbox", "application/mbox");
		mimeMap.put("mc1", "application/vnd.medcalcdata");
		mimeMap.put("mcd", "application/vnd.mcd");
		mimeMap.put("mcurl", "text/vnd.curl.mcurl");
		mimeMap.put("mdb", "application/x-msaccess");
		mimeMap.put("mdi", "image/vnd.ms-modi");
		mimeMap.put("mesh", "model/mesh");
		mimeMap.put("meta4", "application/metalink4+xml");
		mimeMap.put("metalink", "application/metalink+xml");
		mimeMap.put("me", "text/troff");
		mimeMap.put("mets", "application/mets+xml");
		mimeMap.put("mfm", "application/vnd.mfmp");
		mimeMap.put("mft", "application/rpki-manifest");
		mimeMap.put("mgp", "application/vnd.osgeo.mapguide.package");
		mimeMap.put("mgz", "application/vnd.proteus.magazine");
		mimeMap.put("mid", "audio/midi");
		mimeMap.put("midi", "audio/midi");
		mimeMap.put("mie", "application/x-mie");
		mimeMap.put("mif", "application/vnd.mif");
		mimeMap.put("mime", "message/rfc822");
		mimeMap.put("mj2", "video/mj2");
		mimeMap.put("mjp2", "video/mj2");
		mimeMap.put("mk3d", "video/x-matroska");
		mimeMap.put("mka", "audio/x-matroska");
		mimeMap.put("mks", "video/x-matroska");
		mimeMap.put("mkv", "video/x-matroska");
		mimeMap.put("mlp", "application/vnd.dolby.mlp");
		mimeMap.put("mmd", "application/vnd.chipnuts.karaoke-mmd");
		mimeMap.put("mmf", "application/vnd.smaf");
		mimeMap.put("mmr", "image/vnd.fujixerox.edmics-mmr");
		mimeMap.put("mng", "video/x-mng");
		mimeMap.put("mny", "application/x-msmoney");
		mimeMap.put("mobi", "application/x-mobipocket-ebook");
		mimeMap.put("mods", "application/mods+xml");
		mimeMap.put("movie", "video/x-sgi-movie");
		mimeMap.put("mov", "video/quicktime");
		mimeMap.put("mp21", "application/mp21");
		mimeMap.put("mp2a", "audio/mpeg");
		mimeMap.put("mp2", "audio/mpeg");
		mimeMap.put("mp3", "audio/mpeg");
		mimeMap.put("mp4a", "audio/mp4");
		mimeMap.put("mp4s", "application/mp4");
		mimeMap.put("mp4", "video/mp4");
		mimeMap.put("mp4v", "video/mp4");
		mimeMap.put("mpc", "application/vnd.mophun.certificate");
		mimeMap.put("mpeg", "video/mpeg");
		mimeMap.put("mpe", "video/mpeg");
		mimeMap.put("mpg4", "video/mp4");
		mimeMap.put("mpga", "audio/mpeg");
		mimeMap.put("mpg", "video/mpeg");
		mimeMap.put("mpkg", "application/vnd.apple.installer+xml");
		mimeMap.put("mpm", "application/vnd.blueice.multipass");
		mimeMap.put("mpn", "application/vnd.mophun.application");
		mimeMap.put("mpp", "application/vnd.ms-project");
		mimeMap.put("mpt", "application/vnd.ms-project");
		mimeMap.put("mpy", "application/vnd.ibm.minipay");
		mimeMap.put("mqy", "application/vnd.mobius.mqy");
		mimeMap.put("mrc", "application/marc");
		mimeMap.put("mrcx", "application/marcxml+xml");
		mimeMap.put("mscml", "application/mediaservercontrol+xml");
		mimeMap.put("mseed", "application/vnd.fdsn.mseed");
		mimeMap.put("mseq", "application/vnd.mseq");
		mimeMap.put("msf", "application/vnd.epson.msf");
		mimeMap.put("msh", "model/mesh");
		mimeMap.put("msi", "application/x-msdownload");
		mimeMap.put("msl", "application/vnd.mobius.msl");
		mimeMap.put("ms", "text/troff");
		mimeMap.put("msty", "application/vnd.muvee.style");
		mimeMap.put("mts", "model/vnd.mts");
		mimeMap.put("mus", "application/vnd.musician");
		mimeMap.put("musicxml", "application/vnd.recordare.musicxml+xml");
		mimeMap.put("mvb", "application/x-msmediaview");
		mimeMap.put("mwf", "application/vnd.mfer");
		mimeMap.put("mxf", "application/mxf");
		mimeMap.put("mxl", "application/vnd.recordare.musicxml");
		mimeMap.put("mxml", "application/xv+xml");
		mimeMap.put("mxs", "application/vnd.triscape.mxs");
		mimeMap.put("mxu", "video/vnd.mpegurl");
		mimeMap.put("n3", "text/n3");
		mimeMap.put("nb", "application/mathematica");
		mimeMap.put("nbp", "application/vnd.wolfram.player");
		mimeMap.put("nc", "application/x-netcdf");
		mimeMap.put("ncx", "application/x-dtbncx+xml");
		mimeMap.put("nfo", "text/x-nfo");
		mimeMap.put("n-gage", "application/vnd.nokia.n-gage.symbian.install");
		mimeMap.put("ngdat", "application/vnd.nokia.n-gage.data");
		mimeMap.put("nitf", "application/vnd.nitf");
		mimeMap.put("nlu", "application/vnd.neurolanguage.nlu");
		mimeMap.put("nml", "application/vnd.enliven");
		mimeMap.put("nnd", "application/vnd.noblenet-directory");
		mimeMap.put("nns", "application/vnd.noblenet-sealer");
		mimeMap.put("nnw", "application/vnd.noblenet-web");
		mimeMap.put("npx", "image/vnd.net-fpx");
		mimeMap.put("nsc", "application/x-conference");
		mimeMap.put("nsf", "application/vnd.lotus-notes");
		mimeMap.put("ntf", "application/vnd.nitf");
		mimeMap.put("nzb", "application/x-nzb");
		mimeMap.put("oa2", "application/vnd.fujitsu.oasys2");
		mimeMap.put("oa3", "application/vnd.fujitsu.oasys3");
		mimeMap.put("oas", "application/vnd.fujitsu.oasys");
		mimeMap.put("obd", "application/x-msbinder");
		mimeMap.put("obj", "application/x-tgif");
		mimeMap.put("oda", "application/oda");
		mimeMap.put("odb", "application/vnd.oasis.opendocument.database");
		mimeMap.put("odc", "application/vnd.oasis.opendocument.chart");
		mimeMap.put("odf", "application/vnd.oasis.opendocument.formula");
		mimeMap.put("odft", "application/vnd.oasis.opendocument.formula-template");
		mimeMap.put("odg", "application/vnd.oasis.opendocument.graphics");
		mimeMap.put("odi", "application/vnd.oasis.opendocument.image");
		mimeMap.put("odm", "application/vnd.oasis.opendocument.text-master");
		mimeMap.put("odp", "application/vnd.oasis.opendocument.presentation");
		mimeMap.put("ods", "application/vnd.oasis.opendocument.spreadsheet");
		mimeMap.put("odt", "application/vnd.oasis.opendocument.text");
		mimeMap.put("oga", "audio/ogg");
		mimeMap.put("ogg", "audio/ogg");
		mimeMap.put("ogv", "video/ogg");
		mimeMap.put("ogx", "application/ogg");
		mimeMap.put("omdoc", "application/omdoc+xml");
		mimeMap.put("onepkg", "application/onenote");
		mimeMap.put("onetmp", "application/onenote");
		mimeMap.put("onetoc2", "application/onenote");
		mimeMap.put("onetoc", "application/onenote");
		mimeMap.put("opf", "application/oebps-package+xml");
		mimeMap.put("opml", "text/x-opml");
		mimeMap.put("oprc", "application/vnd.palm");
		mimeMap.put("org", "application/vnd.lotus-organizer");
		mimeMap.put("osf", "application/vnd.yamaha.openscoreformat");
		mimeMap.put("osfpvg", "application/vnd.yamaha.openscoreformat.osfpvg+xml");
		mimeMap.put("otc", "application/vnd.oasis.opendocument.chart-template");
		mimeMap.put("otf", "font/otf");
		mimeMap.put("otg", "application/vnd.oasis.opendocument.graphics-template");
		mimeMap.put("oth", "application/vnd.oasis.opendocument.text-web");
		mimeMap.put("oti", "application/vnd.oasis.opendocument.image-template");
		mimeMap.put("otp", "application/vnd.oasis.opendocument.presentation-template");
		mimeMap.put("ots", "application/vnd.oasis.opendocument.spreadsheet-template");
		mimeMap.put("ott", "application/vnd.oasis.opendocument.text-template");
		mimeMap.put("oxps", "application/oxps");
		mimeMap.put("oxt", "application/vnd.openofficeorg.extension");
		mimeMap.put("p10", "application/pkcs10");
		mimeMap.put("p12", "application/x-pkcs12");
		mimeMap.put("p7b", "application/x-pkcs7-certificates");
		mimeMap.put("p7c", "application/pkcs7-mime");
		mimeMap.put("p7m", "application/pkcs7-mime");
		mimeMap.put("p7r", "application/x-pkcs7-certreqresp");
		mimeMap.put("p7s", "application/pkcs7-signature");
		mimeMap.put("p8", "application/pkcs8");
		mimeMap.put("pas", "text/x-pascal");
		mimeMap.put("paw", "application/vnd.pawaafile");
		mimeMap.put("pbd", "application/vnd.powerbuilder6");
		mimeMap.put("pbm", "image/x-portable-bitmap");
		mimeMap.put("pcap", "application/vnd.tcpdump.pcap");
		mimeMap.put("pcf", "application/x-font-pcf");
		mimeMap.put("pcl", "application/vnd.hp-pcl");
		mimeMap.put("pclxl", "application/vnd.hp-pclxl");
		mimeMap.put("pct", "image/x-pict");
		mimeMap.put("pcurl", "application/vnd.curl.pcurl");
		mimeMap.put("pcx", "image/x-pcx");
		mimeMap.put("pdb", "application/vnd.palm");
		mimeMap.put("pdf", "application/pdf");
		mimeMap.put("pfa", "application/x-font-type1");
		mimeMap.put("pfb", "application/x-font-type1");
		mimeMap.put("pfm", "application/x-font-type1");
		mimeMap.put("pfr", "application/font-tdpfr");
		mimeMap.put("pfx", "application/x-pkcs12");
		mimeMap.put("pgm", "image/x-portable-graymap");
		mimeMap.put("pgn", "application/x-chess-pgn");
		mimeMap.put("pgp", "application/pgp-encrypted");
		mimeMap.put("pic", "image/x-pict");
		mimeMap.put("pkg", "application/octet-stream");
		mimeMap.put("pki", "application/pkixcmp");
		mimeMap.put("pkipath", "application/pkix-pkipath");
		mimeMap.put("plb", "application/vnd.3gpp.pic-bw-large");
		mimeMap.put("plc", "application/vnd.mobius.plc");
		mimeMap.put("plf", "application/vnd.pocketlearn");
		mimeMap.put("pls", "application/pls+xml");
		mimeMap.put("pml", "application/vnd.ctc-posml");
		mimeMap.put("png", "image/png");
		mimeMap.put("pnm", "image/x-portable-anymap");
		mimeMap.put("portpkg", "application/vnd.macports.portpkg");
		mimeMap.put("pot", "application/vnd.ms-powerpoint");
		mimeMap.put("potm", "application/vnd.ms-powerpoint.template.macroenabled.12");
		mimeMap.put("potx", "application/vnd.openxmlformats-officedocument.presentationml.template");
		mimeMap.put("ppam", "application/vnd.ms-powerpoint.addin.macroenabled.12");
		mimeMap.put("ppd", "application/vnd.cups-ppd");
		mimeMap.put("ppm", "image/x-portable-pixmap");
		mimeMap.put("pps", "application/vnd.ms-powerpoint");
		mimeMap.put("ppsm", "application/vnd.ms-powerpoint.slideshow.macroenabled.12");
		mimeMap.put("ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow");
		mimeMap.put("ppt", "application/vnd.ms-powerpoint");
		mimeMap.put("pptm", "application/vnd.ms-powerpoint.presentation.macroenabled.12");
		mimeMap.put("pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
		mimeMap.put("pqa", "application/vnd.palm");
		mimeMap.put("prc", "application/x-mobipocket-ebook");
		mimeMap.put("pre", "application/vnd.lotus-freelance");
		mimeMap.put("prf", "application/pics-rules");
		mimeMap.put("ps", "application/postscript");
		mimeMap.put("psb", "application/vnd.3gpp.pic-bw-small");
		mimeMap.put("psd", "image/vnd.adobe.photoshop");
		mimeMap.put("psf", "application/x-font-linux-psf");
		mimeMap.put("pskcxml", "application/pskc+xml");
		mimeMap.put("p", "text/x-pascal");
		mimeMap.put("ptid", "application/vnd.pvi.ptid1");
		mimeMap.put("pub", "application/x-mspublisher");
		mimeMap.put("pvb", "application/vnd.3gpp.pic-bw-var");
		mimeMap.put("pwn", "application/vnd.3m.post-it-notes");
		mimeMap.put("pya", "audio/vnd.ms-playready.media.pya");
		mimeMap.put("pyv", "video/vnd.ms-playready.media.pyv");
		mimeMap.put("qam", "application/vnd.epson.quickanime");
		mimeMap.put("qbo", "application/vnd.intu.qbo");
		mimeMap.put("qfx", "application/vnd.intu.qfx");
		mimeMap.put("qps", "application/vnd.publishare-delta-tree");
		mimeMap.put("qt", "video/quicktime");
		mimeMap.put("qwd", "application/vnd.quark.quarkxpress");
		mimeMap.put("qwt", "application/vnd.quark.quarkxpress");
		mimeMap.put("qxb", "application/vnd.quark.quarkxpress");
		mimeMap.put("qxd", "application/vnd.quark.quarkxpress");
		mimeMap.put("qxl", "application/vnd.quark.quarkxpress");
		mimeMap.put("qxt", "application/vnd.quark.quarkxpress");
		mimeMap.put("ra", "audio/x-pn-realaudio");
		mimeMap.put("ram", "audio/x-pn-realaudio");
		mimeMap.put("rar", "application/x-rar-compressed");
		mimeMap.put("ras", "image/x-cmu-raster");
		mimeMap.put("rcprofile", "application/vnd.ipunplugged.rcprofile");
		mimeMap.put("rdf", "application/rdf+xml");
		mimeMap.put("rdz", "application/vnd.data-vision.rdz");
		mimeMap.put("rep", "application/vnd.businessobjects");
		mimeMap.put("res", "application/x-dtbresource+xml");
		mimeMap.put("rgb", "image/x-rgb");
		mimeMap.put("rif", "application/reginfo+xml");
		mimeMap.put("rip", "audio/vnd.rip");
		mimeMap.put("ris", "application/x-research-info-systems");
		mimeMap.put("rl", "application/resource-lists+xml");
		mimeMap.put("rlc", "image/vnd.fujixerox.edmics-rlc");
		mimeMap.put("rld", "application/resource-lists-diff+xml");
		mimeMap.put("rm", "application/vnd.rn-realmedia");
		mimeMap.put("rmi", "audio/midi");
		mimeMap.put("rmp", "audio/x-pn-realaudio-plugin");
		mimeMap.put("rms", "application/vnd.jcp.javame.midlet-rms");
		mimeMap.put("rmvb", "application/vnd.rn-realmedia-vbr");
		mimeMap.put("rnc", "application/relax-ng-compact-syntax");
		mimeMap.put("roa", "application/rpki-roa");
		mimeMap.put("roff", "text/troff");
		mimeMap.put("rp9", "application/vnd.cloanto.rp9");
		mimeMap.put("rpss", "application/vnd.nokia.radio-presets");
		mimeMap.put("rpst", "application/vnd.nokia.radio-preset");
		mimeMap.put("rq", "application/sparql-query");
		mimeMap.put("rs", "application/rls-services+xml");
		mimeMap.put("rsd", "application/rsd+xml");
		mimeMap.put("rss", "application/rss+xml");
		mimeMap.put("rtf", "application/rtf");
		mimeMap.put("rtx", "text/richtext");
		mimeMap.put("s3m", "audio/s3m");
		mimeMap.put("saf", "application/vnd.yamaha.smaf-audio");
		mimeMap.put("sbml", "application/sbml+xml");
		mimeMap.put("sc", "application/vnd.ibm.secure-container");
		mimeMap.put("scd", "application/x-msschedule");
		mimeMap.put("scm", "application/vnd.lotus-screencam");
		mimeMap.put("scq", "application/scvp-cv-request");
		mimeMap.put("scs", "application/scvp-cv-response");
		mimeMap.put("scurl", "text/vnd.curl.scurl");
		mimeMap.put("sda", "application/vnd.stardivision.draw");
		mimeMap.put("sdc", "application/vnd.stardivision.calc");
		mimeMap.put("sdd", "application/vnd.stardivision.impress");
		mimeMap.put("sdkd", "application/vnd.solent.sdkm+xml");
		mimeMap.put("sdkm", "application/vnd.solent.sdkm+xml");
		mimeMap.put("sdp", "application/sdp");
		mimeMap.put("sdw", "application/vnd.stardivision.writer");
		mimeMap.put("see", "application/vnd.seemail");
		mimeMap.put("seed", "application/vnd.fdsn.seed");
		mimeMap.put("sema", "application/vnd.sema");
		mimeMap.put("semd", "application/vnd.semd");
		mimeMap.put("semf", "application/vnd.semf");
		mimeMap.put("ser", "application/java-serialized-object");
		mimeMap.put("setpay", "application/set-payment-initiation");
		mimeMap.put("setreg", "application/set-registration-initiation");
		mimeMap.put("sfd-hdstx", "application/vnd.hydrostatix.sof-data");
		mimeMap.put("sfs", "application/vnd.spotfire.sfs");
		mimeMap.put("sfv", "text/x-sfv");
		mimeMap.put("sgi", "image/sgi");
		mimeMap.put("sgl", "application/vnd.stardivision.writer-global");
		mimeMap.put("sgml", "text/sgml");
		mimeMap.put("sgm", "text/sgml");
		mimeMap.put("sh", "application/x-sh");
		mimeMap.put("shar", "application/x-shar");
		mimeMap.put("shf", "application/shf+xml");
		mimeMap.put("sid", "image/x-mrsid-image");
		mimeMap.put("sig", "application/pgp-signature");
		mimeMap.put("sil", "audio/silk");
		mimeMap.put("silo", "model/mesh");
		mimeMap.put("sis", "application/vnd.symbian.install");
		mimeMap.put("sisx", "application/vnd.symbian.install");
		mimeMap.put("sit", "application/x-stuffit");
		mimeMap.put("sitx", "application/x-stuffitx");
		mimeMap.put("skd", "application/vnd.koan");
		mimeMap.put("skm", "application/vnd.koan");
		mimeMap.put("skp", "application/vnd.koan");
		mimeMap.put("skt", "application/vnd.koan");
		mimeMap.put("sldm", "application/vnd.ms-powerpoint.slide.macroenabled.12");
		mimeMap.put("sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide");
		mimeMap.put("slt", "application/vnd.epson.salt");
		mimeMap.put("sm", "application/vnd.stepmania.stepchart");
		mimeMap.put("smf", "application/vnd.stardivision.math");
		mimeMap.put("smi", "application/smil+xml");
		mimeMap.put("smil", "application/smil+xml");
		mimeMap.put("smv", "video/x-smv");
		mimeMap.put("smzip", "application/vnd.stepmania.package");
		mimeMap.put("snd", "audio/basic");
		mimeMap.put("snf", "application/x-font-snf");
		mimeMap.put("so", "application/octet-stream");
		mimeMap.put("spc", "application/x-pkcs7-certificates");
		mimeMap.put("spf", "application/vnd.yamaha.smaf-phrase");
		mimeMap.put("spl", "application/x-futuresplash");
		mimeMap.put("spot", "text/vnd.in3d.spot");
		mimeMap.put("spp", "application/scvp-vp-response");
		mimeMap.put("spq", "application/scvp-vp-request");
		mimeMap.put("spx", "audio/ogg");
		mimeMap.put("sql", "application/x-sql");
		mimeMap.put("src", "application/x-wais-source");
		mimeMap.put("srt", "application/x-subrip");
		mimeMap.put("sru", "application/sru+xml");
		mimeMap.put("srx", "application/sparql-results+xml");
		mimeMap.put("ssdl", "application/ssdl+xml");
		mimeMap.put("sse", "application/vnd.kodak-descriptor");
		mimeMap.put("ssf", "application/vnd.epson.ssf");
		mimeMap.put("ssml", "application/ssml+xml");
		mimeMap.put("st", "application/vnd.sailingtracker.track");
		mimeMap.put("stc", "application/vnd.sun.xml.calc.template");
		mimeMap.put("std", "application/vnd.sun.xml.draw.template");
		mimeMap.put("s", "text/x-asm");
		mimeMap.put("stf", "application/vnd.wt.stf");
		mimeMap.put("sti", "application/vnd.sun.xml.impress.template");
		mimeMap.put("stk", "application/hyperstudio");
		mimeMap.put("stl", "application/vnd.ms-pki.stl");
		mimeMap.put("str", "application/vnd.pg.format");
		mimeMap.put("stw", "application/vnd.sun.xml.writer.template");
		mimeMap.put("sub", "image/vnd.dvb.subtitle");
		mimeMap.put("sub", "text/vnd.dvb.subtitle");
		mimeMap.put("sus", "application/vnd.sus-calendar");
		mimeMap.put("susp", "application/vnd.sus-calendar");
		mimeMap.put("sv4cpio", "application/x-sv4cpio");
		mimeMap.put("sv4crc", "application/x-sv4crc");
		mimeMap.put("svc", "application/vnd.dvb.service");
		mimeMap.put("svd", "application/vnd.svd");
		mimeMap.put("svg", "image/svg+xml");
		mimeMap.put("svgz", "image/svg+xml");
		mimeMap.put("swa", "application/x-director");
		mimeMap.put("swf", "application/x-shockwave-flash");
		mimeMap.put("swi", "application/vnd.aristanetworks.swi");
		mimeMap.put("sxc", "application/vnd.sun.xml.calc");
		mimeMap.put("sxd", "application/vnd.sun.xml.draw");
		mimeMap.put("sxg", "application/vnd.sun.xml.writer.global");
		mimeMap.put("sxi", "application/vnd.sun.xml.impress");
		mimeMap.put("sxm", "application/vnd.sun.xml.math");
		mimeMap.put("sxw", "application/vnd.sun.xml.writer");
		mimeMap.put("t3", "application/x-t3vm-image");
		mimeMap.put("taglet", "application/vnd.mynfc");
		mimeMap.put("tao", "application/vnd.tao.intent-module-archive");
		mimeMap.put("tar", "application/x-tar");
		mimeMap.put("tcap", "application/vnd.3gpp2.tcap");
		mimeMap.put("tcl", "application/x-tcl");
		mimeMap.put("teacher", "application/vnd.smart.teacher");
		mimeMap.put("tei", "application/tei+xml");
		mimeMap.put("teicorpus", "application/tei+xml");
		mimeMap.put("tex", "application/x-tex");
		mimeMap.put("texi", "application/x-texinfo");
		mimeMap.put("texinfo", "application/x-texinfo");
		mimeMap.put("text", "text/plain");
		mimeMap.put("tfi", "application/thraud+xml");
		mimeMap.put("tfm", "application/x-tex-tfm");
		mimeMap.put("tga", "image/x-tga");
		mimeMap.put("thmx", "application/vnd.ms-officetheme");
		mimeMap.put("tiff", "image/tiff");
		mimeMap.put("tif", "image/tiff");
		mimeMap.put("tmo", "application/vnd.tmobile-livetv");
		mimeMap.put("torrent", "application/x-bittorrent");
		mimeMap.put("tpl", "application/vnd.groove-tool-template");
		mimeMap.put("tpt", "application/vnd.trid.tpt");
		mimeMap.put("tra", "application/vnd.trueapp");
		mimeMap.put("trm", "application/x-msterminal");
		mimeMap.put("tr", "text/troff");
		mimeMap.put("tsd", "application/timestamped-data");
		mimeMap.put("tsv", "text/tab-separated-values");
		mimeMap.put("ttc", "font/collection");
		mimeMap.put("t", "text/troff");
		mimeMap.put("ttf", "font/ttf");
		mimeMap.put("ttl", "text/turtle");
		mimeMap.put("twd", "application/vnd.simtech-mindmapper");
		mimeMap.put("twds", "application/vnd.simtech-mindmapper");
		mimeMap.put("txd", "application/vnd.genomatix.tuxedo");
		mimeMap.put("txf", "application/vnd.mobius.txf");
		mimeMap.put("txt", "text/plain");
		mimeMap.put("u32", "application/x-authorware-bin");
		mimeMap.put("udeb", "application/x-debian-package");
		mimeMap.put("ufd", "application/vnd.ufdl");
		mimeMap.put("ufdl", "application/vnd.ufdl");
		mimeMap.put("ulx", "application/x-glulx");
		mimeMap.put("umj", "application/vnd.umajin");
		mimeMap.put("unityweb", "application/vnd.unity");
		mimeMap.put("uoml", "application/vnd.uoml+xml");
		mimeMap.put("uris", "text/uri-list");
		mimeMap.put("uri", "text/uri-list");
		mimeMap.put("urls", "text/uri-list");
		mimeMap.put("ustar", "application/x-ustar");
		mimeMap.put("utz", "application/vnd.uiq.theme");
		mimeMap.put("uu", "text/x-uuencode");
		mimeMap.put("uva", "audio/vnd.dece.audio");
		mimeMap.put("uvd", "application/vnd.dece.data");
		mimeMap.put("uvf", "application/vnd.dece.data");
		mimeMap.put("uvg", "image/vnd.dece.graphic");
		mimeMap.put("uvh", "video/vnd.dece.hd");
		mimeMap.put("uvi", "image/vnd.dece.graphic");
		mimeMap.put("uvm", "video/vnd.dece.mobile");
		mimeMap.put("uvp", "video/vnd.dece.pd");
		mimeMap.put("uvs", "video/vnd.dece.sd");
		mimeMap.put("uvt", "application/vnd.dece.ttml+xml");
		mimeMap.put("uvu", "video/vnd.uvvu.mp4");
		mimeMap.put("uvva", "audio/vnd.dece.audio");
		mimeMap.put("uvvd", "application/vnd.dece.data");
		mimeMap.put("uvvf", "application/vnd.dece.data");
		mimeMap.put("uvvg", "image/vnd.dece.graphic");
		mimeMap.put("uvvh", "video/vnd.dece.hd");
		mimeMap.put("uvvi", "image/vnd.dece.graphic");
		mimeMap.put("uvvm", "video/vnd.dece.mobile");
		mimeMap.put("uvvp", "video/vnd.dece.pd");
		mimeMap.put("uvvs", "video/vnd.dece.sd");
		mimeMap.put("uvvt", "application/vnd.dece.ttml+xml");
		mimeMap.put("uvvu", "video/vnd.uvvu.mp4");
		mimeMap.put("uvv", "video/vnd.dece.video");
		mimeMap.put("uvvv", "video/vnd.dece.video");
		mimeMap.put("uvvx", "application/vnd.dece.unspecified");
		mimeMap.put("uvvz", "application/vnd.dece.zip");
		mimeMap.put("uvx", "application/vnd.dece.unspecified");
		mimeMap.put("uvz", "application/vnd.dece.zip");
		mimeMap.put("vcard", "text/vcard");
		mimeMap.put("vcd", "application/x-cdlink");
		mimeMap.put("vcf", "text/x-vcard");
		mimeMap.put("vcg", "application/vnd.groove-vcard");
		mimeMap.put("vcs", "text/x-vcalendar");
		mimeMap.put("vcx", "application/vnd.vcx");
		mimeMap.put("vis", "application/vnd.visionary");
		mimeMap.put("viv", "video/vnd.vivo");
		mimeMap.put("vob", "video/x-ms-vob");
		mimeMap.put("vor", "application/vnd.stardivision.writer");
		mimeMap.put("vox", "application/x-authorware-bin");
		mimeMap.put("vrml", "model/vrml");
		mimeMap.put("vsd", "application/vnd.visio");
		mimeMap.put("vsf", "application/vnd.vsf");
		mimeMap.put("vss", "application/vnd.visio");
		mimeMap.put("vst", "application/vnd.visio");
		mimeMap.put("vsw", "application/vnd.visio");
		mimeMap.put("vtu", "model/vnd.vtu");
		mimeMap.put("vxml", "application/voicexml+xml");
		mimeMap.put("w3d", "application/x-director");
		mimeMap.put("wad", "application/x-doom");
		mimeMap.put("wav", "audio/x-wav");
		mimeMap.put("wax", "audio/x-ms-wax");
		mimeMap.put("wbmp", "image/vnd.wap.wbmp");
		mimeMap.put("wbs", "application/vnd.criticaltools.wbs+xml");
		mimeMap.put("wbxml", "application/vnd.wap.wbxml");
		mimeMap.put("wcm", "application/vnd.ms-works");
		mimeMap.put("wdb", "application/vnd.ms-works");
		mimeMap.put("wdp", "image/vnd.ms-photo");
		mimeMap.put("weba", "audio/webm");
		mimeMap.put("webm", "video/webm");
		mimeMap.put("webp", "image/webp");
		mimeMap.put("wg", "application/vnd.pmi.widget");
		mimeMap.put("wgt", "application/widget");
		mimeMap.put("wks", "application/vnd.ms-works");
		mimeMap.put("wma", "audio/x-ms-wma");
		mimeMap.put("wmd", "application/x-ms-wmd");
		mimeMap.put("wmf", "application/x-msmetafile");
		mimeMap.put("wmlc", "application/vnd.wap.wmlc");
		mimeMap.put("wmlsc", "application/vnd.wap.wmlscriptc");
		mimeMap.put("wmls", "text/vnd.wap.wmlscript");
		mimeMap.put("wml", "text/vnd.wap.wml");
		mimeMap.put("wm", "video/x-ms-wm");
		mimeMap.put("wmv", "video/x-ms-wmv");
		mimeMap.put("wmx", "video/x-ms-wmx");
		mimeMap.put("wmz", "application/x-msmetafile");
		mimeMap.put("wmz", "application/x-ms-wmz");
		mimeMap.put("woff2", "font/woff2");
		mimeMap.put("woff", "font/woff");
		mimeMap.put("wpd", "application/vnd.wordperfect");
		mimeMap.put("wpl", "application/vnd.ms-wpl");
		mimeMap.put("wps", "application/vnd.ms-works");
		mimeMap.put("wqd", "application/vnd.wqd");
		mimeMap.put("wri", "application/x-mswrite");
		mimeMap.put("wrl", "model/vrml");
		mimeMap.put("wsdl", "application/wsdl+xml");
		mimeMap.put("wspolicy", "application/wspolicy+xml");
		mimeMap.put("wtb", "application/vnd.webturbo");
		mimeMap.put("wvx", "video/x-ms-wvx");
		mimeMap.put("x32", "application/x-authorware-bin");
		mimeMap.put("x3db", "model/x3d+binary");
		mimeMap.put("x3dbz", "model/x3d+binary");
		mimeMap.put("x3d", "model/x3d+xml");
		mimeMap.put("x3dv", "model/x3d+vrml");
		mimeMap.put("x3dvz", "model/x3d+vrml");
		mimeMap.put("x3dz", "model/x3d+xml");
		mimeMap.put("xaml", "application/xaml+xml");
		mimeMap.put("xap", "application/x-silverlight-app");
		mimeMap.put("xar", "application/vnd.xara");
		mimeMap.put("xbap", "application/x-ms-xbap");
		mimeMap.put("xbd", "application/vnd.fujixerox.docuworks.binder");
		mimeMap.put("xbm", "image/x-xbitmap");
		mimeMap.put("xdf", "application/xcap-diff+xml");
		mimeMap.put("xdm", "application/vnd.syncml.dm+xml");
		mimeMap.put("xdp", "application/vnd.adobe.xdp+xml");
		mimeMap.put("xdssc", "application/dssc+xml");
		mimeMap.put("xdw", "application/vnd.fujixerox.docuworks");
		mimeMap.put("xenc", "application/xenc+xml");
		mimeMap.put("xer", "application/patch-ops-error+xml");
		mimeMap.put("xfdf", "application/vnd.adobe.xfdf");
		mimeMap.put("xfdl", "application/vnd.xfdl");
		mimeMap.put("xht", "application/xhtml+xml");
		mimeMap.put("xhtml", "application/xhtml+xml");
		mimeMap.put("xhvml", "application/xv+xml");
		mimeMap.put("xif", "image/vnd.xiff");
		mimeMap.put("xla", "application/vnd.ms-excel");
		mimeMap.put("xlam", "application/vnd.ms-excel.addin.macroenabled.12");
		mimeMap.put("xlc", "application/vnd.ms-excel");
		mimeMap.put("xlf", "application/x-xliff+xml");
		mimeMap.put("xlm", "application/vnd.ms-excel");
		mimeMap.put("xls", "application/vnd.ms-excel");
		mimeMap.put("xlsb", "application/vnd.ms-excel.sheet.binary.macroenabled.12");
		mimeMap.put("xlsm", "application/vnd.ms-excel.sheet.macroenabled.12");
		mimeMap.put("xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
		mimeMap.put("xlt", "application/vnd.ms-excel");
		mimeMap.put("xltm", "application/vnd.ms-excel.template.macroenabled.12");
		mimeMap.put("xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template");
		mimeMap.put("xlw", "application/vnd.ms-excel");
		mimeMap.put("xm", "audio/xm");
		mimeMap.put("xml", "application/xml");
		mimeMap.put("xo", "application/vnd.olpc-sugar");
		mimeMap.put("xop", "application/xop+xml");
		mimeMap.put("xpi", "application/x-xpinstall");
		mimeMap.put("xpl", "application/xproc+xml");
		mimeMap.put("xpm", "image/x-xpixmap");
		mimeMap.put("xpr", "application/vnd.is-xpr");
		mimeMap.put("xps", "application/vnd.ms-xpsdocument");
		mimeMap.put("xpw", "application/vnd.intercon.formnet");
		mimeMap.put("xpx", "application/vnd.intercon.formnet");
		mimeMap.put("xsl", "application/xml");
		mimeMap.put("xslt", "application/xslt+xml");
		mimeMap.put("xsm", "application/vnd.syncml+xml");
		mimeMap.put("xspf", "application/xspf+xml");
		mimeMap.put("xul", "application/vnd.mozilla.xul+xml");
		mimeMap.put("xvm", "application/xv+xml");
		mimeMap.put("xvml", "application/xv+xml");
		mimeMap.put("xwd", "image/x-xwindowdump");
		mimeMap.put("xyz", "chemical/x-xyz");
		mimeMap.put("xz", "application/x-xz");
		mimeMap.put("yang", "application/yang");
		mimeMap.put("yin", "application/yin+xml");
		mimeMap.put("z1", "application/x-zmachine");
		mimeMap.put("z2", "application/x-zmachine");
		mimeMap.put("z3", "application/x-zmachine");
		mimeMap.put("z4", "application/x-zmachine");
		mimeMap.put("z5", "application/x-zmachine");
		mimeMap.put("z6", "application/x-zmachine");
		mimeMap.put("z7", "application/x-zmachine");
		mimeMap.put("z8", "application/x-zmachine");
		mimeMap.put("zaz", "application/vnd.zzazz.deck+xml");
		mimeMap.put("zip", "application/zip");
		mimeMap.put("zir", "application/vnd.zul");
		mimeMap.put("zirz", "application/vnd.zul");
		mimeMap.put("zmm", "application/vnd.handheld-entertainment+xml");

	}

	public static Pattern URL_REGEX = Pattern
			.compile("" + "(https?:\\/\\/(?:www\\.|(?!www))" + "[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|"
					+ "www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|"
					+ "https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9]+\\.[^\\s]{2,}|" + "www\\.[a-zA-Z0-9]+\\.[^\\s]{2,})");

	public static List<String> matchAllStrURLs(String str) {
		List<String> matches = new ArrayList<String>();
		Matcher m = URL_REGEX.matcher(str);

		while (m.find()) {
			matches.add(m.group());
		}
		return matches;
	}

	public static List<URL> matchAllURLs(String str) {
		List<URL> matches = new ArrayList<URL>();
		Matcher m = URL_REGEX.matcher(str);

		while (m.find()) {
			try {
				matches.add(new URL(m.group()));
			} catch (MalformedURLException e) {
				System.err.print(
						"There was an issue where a URL accepted by the URL_REGEX pattern was not accepted by java.net.URL's constructor.\n"
								+ "URL: " + m.group() + "\n" + "Please create an issue on Github at:\n"
								+ "https://github.com/Aaron-Pazdera/MonikaBot");
			}
		}
		return matches;
	}

	public static String extensionFromURL(String url) throws MalformedURLException {
		return extensionFromURL(new URL(url));
	}

	public static String extensionFromURL(URL url) {
		return FilenameUtils.getExtension(url.getPath());
	}

	public static String guessMimeFromURL(String url) throws MalformedURLException {
		return guessMimeFromURL(new URL(url));
	}

	public static String guessMimeFromURL(URL url) {
		// The replace deals with twitter extensions. The ends with deals with trailing
		// slashes, which would mess up the split and cause illegal array accesses.
		String path = url.getPath().replace(":large", "");
		path = path.endsWith("/") ? path.substring(0, path.length() - 1) : path;
		String[] pathsplit = path.contains("/") ? path.split("/") : new String[] { path };
		String filename = pathsplit[pathsplit.length - 1];
		String[] extensionsplit = filename.split("\\.");
		String extension = extensionsplit[extensionsplit.length - 1];
		return mimeMap.get(extension);

	}

	public static boolean isImage(String url) throws MalformedURLException {
		return isImage(new URL(url));
	}

	public static boolean isImage(URL url) {
		String mime = guessMimeFromURL(url);
		if (mime == null) {
			return false;
		}

		return mime.contains("image");
	}

	// Returns null if isn't an image, or it's a gif
	public static BufferedImage openImage(URL imgURL) throws IOException {

		// Due to a Java 8 bug in ImageIO, cannot read animated gifs.
		if (imgURL.getPath().contains(".gif")) {
			return null;
		}

		final HttpURLConnection connection = (HttpURLConnection) imgURL.openConnection();
		connection.setRequestProperty("User-Agent",
				"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.65 Safari/537.31");

		int code = connection.getResponseCode();
		if (code == 403) {
			System.err.println("Error 403: Forbidden for: " + imgURL);
			return null;
		} else if (code == 404) {
			System.err.println("Error 404: Not Found for: " + imgURL);
			return null;
		} else if (code < 500 && code >= 400) {
			System.err.println("Client error (" + code + ") for: " + imgURL);
			return null;
		} else if (code < 600 && code >= 500) {
			System.err.println("Server error (" + code + ") for: " + imgURL);
			return null;
		}

		InputStream s = connection.getInputStream();
		return ImageIO.read(s);
	}

	private static File downloadFolder = null;
	static {
		downloadFolder = new File(System.getProperty("user.dir") + File.separator + "MonikaBot-Rebase");
		if (!downloadFolder.isDirectory())
			if (!downloadFolder.mkdirs())
				throw new IllegalStateException("Could not create rebase folder.");
	}

	public static File downloadURL(String url) throws MalformedURLException, IOException {
		URL u = null;
		try {
			u = new URL(url);
		} catch (MalformedURLException e) {
			e.printStackTrace();
			return null;
		}

		// At first take the file name from the url
		String fileName = FilenameUtils.getName(u.getPath());

		// Now, find a place to put it. Don't overwrite anything already existing.
		File f = null;
		while (f == null) {
			f = new File(downloadFolder.getPath() + File.separator + fileName);
			System.out.println(f.getPath());
			if (f.exists()) {
				f = null;
				if (fileName.contains(".")) {
					String[] nameSpt = fileName.split("\\.");
					nameSpt[nameSpt.length - 2] += new Random().nextInt(10);
					fileName = String.join(".", nameSpt);
				} else {
					fileName += new Random().nextInt(10);
				}
			}
		}

		final HttpURLConnection connection = (HttpURLConnection) u.openConnection();
		connection.setRequestProperty("User-Agent",
				"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.65 Safari/537.31");

		int code = connection.getResponseCode();
		if (code == 403) {
			System.err.println("Error 403: Forbidden for: " + u);
			return null;
		} else if (code == 404) {
			System.err.println("Error 404: Not Found for: " + u);
			return null;
		} else if (code < 500 && code >= 400) {
			System.err.println("Client error (" + code + ") for: " + u);
			return null;
		} else if (code < 600 && code >= 500) {
			System.err.println("Server error (" + code + ") for: " + u);
			return null;
		}

		InputStream s = new BufferedInputStream(connection.getInputStream());
		FileOutputStream out = new FileOutputStream(f);
		IOUtils.copy(s, out);
		return f;
	}

}
